contact_links:
  - name: File an issue with structured data pre-filled
    url: https://github.com/lukehefson/all-the-structured-data/issues/new?assignees=lukehefson&labels=enhancement%2C+question&title=A+pre-filled+title&milestone=a+milestone&projects=lukehefson/all-the-structured-data/1
    about: Automate every bit of structured data possible upon issue submission
